export enum Storage {
    API = 'api-storage',
    BackgroundImage = 'background-image-storage',
    UserCard = 'usercard-storage',
    Instruct = 'instruct-storage',
    Logs = 'logstate-storage',
    Samplers = 'samplerstate-storage',
    TTS = 'tts-data-storage',
    ColorState = 'colorscheme-storage',
    CharacterSearch = 'storage-character-search',
    ChatStyle = 'storage-chat-text-styling',
    Language = 'language-storage',
    LiteLLMModels = 'litellm-models-storage',
    LemonSlice = 'lemonslice-storage',
    MouthSprites = 'mouth-sprites-storage',
}
